Set-Location 'C:\vaxplan-main'
$env:DATABASE_URL='postgresql://postgres@localhost:5432/vaxplan'
$env:PORT='5000'
$env:SESSION_SECRET='local-dev-session-secret-change-before-production'
$env:NODE_ENV='production'
$env:SKIP_DB_BOOTSTRAP='1'
$env:SKIP_OUTSIDE_VILLAGES_CACHE='1'
$env:SESSION_STORE='memory'
$env:SESSION_SECURE_COOKIE='false'
$env:LOCAL_HTTP_SESSION='1'
& 'C:\Program Files\nodejs\node.exe' 'dist\index.cjs' *> 'C:\vaxplan-main\vaxplan-node-repl-server.log'
