import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "../shared/schema.js";
import { sql, eq } from "drizzle-orm";
import * as fs from "fs";
import * as path from "path";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error("❌ DATABASE_URL is not set!");
  process.exit(1);
}

// Helper to convert serialized date strings back to Date objects
function parseDates(row: any) {
  if (!row) return row;
  const result = { ...row };
  for (const key of Object.keys(result)) {
    const val = result[key];
    if (val && typeof val === "string") {
      const isDateKey = key.toLowerCase().endsWith("at") ||
                        key.toLowerCase().endsWith("date") ||
                        key.toLowerCase().endsWith("from") ||
                        key.toLowerCase().endsWith("to");
      const isIsoString = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(val);
      
      if (isDateKey || isIsoString) {
        const parsed = Date.parse(val);
        if (!isNaN(parsed)) {
          result[key] = new Date(val);
        }
      }
    }
  }
  return result;
}

// Helper to serialize objects/arrays for JSON/JSONB columns
function serializeJsonFields(row: any) {
  if (!row) return row;
  const result = { ...row };
  for (const key of Object.keys(result)) {
    const val = result[key];
    if (val !== null && typeof val === "object" && !(val instanceof Date)) {
      result[key] = JSON.stringify(val);
    }
  }
  return result;
}

async function importAll() {
  const jsonPath = path.join(process.cwd(), "localhost_data.json");
  if (!fs.existsSync(jsonPath)) {
    console.error(`❌ Data file not found at ${jsonPath}`);
    process.exit(1);
  }

  console.log("📖 Reading localhost_data.json...");
  const exportData = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));

  console.log("🔌 Connecting to production database...");
  const pool = new pg.Pool({ connectionString: databaseUrl });
  const db = drizzle(pool, { schema });

  const tablesToImport = [
    { name: "users", table: schema.users, key: "id", dbName: "users", hasIdentity: false },
    { name: "userRoles", table: schema.userRoles, key: "id", dbName: "user_roles", hasIdentity: true },
    { name: "userPermissions", table: schema.userPermissions, key: "id", dbName: "user_permissions", hasIdentity: true },
    { name: "microplans", table: schema.microplans, key: "id", dbName: "microplans", hasIdentity: true },
    { name: "chvProfiles", table: schema.chvProfiles, key: "id", dbName: "chv_profiles", hasIdentity: true },
    { name: "facilityStaff", table: schema.facilityStaff, key: "id", dbName: "facility_staff", hasIdentity: true },
    { name: "entityHistoryVersions", table: schema.entityHistoryVersions, key: "id", dbName: "entity_history_versions", hasIdentity: true },
    { name: "userAssignmentHistory", table: schema.userAssignmentHistory, key: "id", dbName: "user_assignment_history", hasIdentity: true },
    { name: "facilityHistoryVersions", table: schema.facilityHistoryVersions, key: "id", dbName: "facility_history_versions", hasIdentity: true },
    { name: "communityHistoryVersions", table: schema.communityHistoryVersions, key: "id", dbName: "community_history_versions", hasIdentity: true },
    { name: "populationHistoryVersions", table: schema.populationHistoryVersions, key: "id", dbName: "population_history_versions", hasIdentity: true },
    { name: "vaccineScheduleHistoryVersions", table: schema.vaccineScheduleHistoryVersions, key: "id", dbName: "vaccine_schedule_history_versions", hasIdentity: true },
    { name: "stockReferenceHistoryVersions", table: schema.stockReferenceHistoryVersions, key: "id", dbName: "stock_reference_history_versions", hasIdentity: true },
  ];

  for (const { name, table, key, dbName, hasIdentity } of tablesToImport) {
    const rows = exportData[name];
    if (!rows || rows.length === 0) {
      console.log(`ℹ️ No rows to import for ${name}`);
      continue;
    }

    console.log(`⚙️ Importing ${rows.length} rows into ${name} (db: ${dbName})...`);

    // Temporarily bypass GENERATED ALWAYS identity restriction
    if (hasIdentity) {
      try {
        await db.execute(sql.raw(`ALTER TABLE "${dbName}" ALTER COLUMN "${key}" SET GENERATED BY DEFAULT;`));
        console.log(`   🔓 Temporary identity bypass enabled for ${dbName}`);
      } catch (err: any) {
        console.warn(`   ⚠️ Warning enabling identity bypass for ${dbName}:`, err.message);
      }
    }

    let inserted = 0;
    let skipped = 0;

    for (const rawRow of rows) {
      let row = parseDates(rawRow);
      row = serializeJsonFields(row);
      try {
        const existing = await db
          .select()
          .from(table)
          .where(eq(table[key], row[key]))
          .limit(1);

        if (existing.length > 0) {
          const tenantId = row.tenantId || existing[0].tenantId;
          const isLocalTenant = tenantId === undefined || tenantId === null || tenantId === "ZMB" || tenantId.includes("4bb7abba");
          
          if (!isLocalTenant) {
            skipped++;
            continue;
          }

          const { [key]: _, ...updateFields } = row;
          await db
            .update(table)
            .set(updateFields)
            .where(eq(table[key], row[key]));
        } else {
          await db.insert(table).values(row);
        }
        inserted++;
      } catch (err: any) {
        console.error(`   ⚠️ Error importing row ${row[key]} in ${name}:`);
        console.error(err);
      }
    }

    // Re-enable GENERATED ALWAYS identity restriction
    if (hasIdentity) {
      try {
        await db.execute(sql.raw(`ALTER TABLE "${dbName}" ALTER COLUMN "${key}" SET GENERATED ALWAYS;`));
        console.log(`   🔒 Identity verification re-enabled for ${dbName}`);
      } catch (err: any) {
        console.warn(`   ⚠️ Warning restoring identity for ${dbName}:`, err.message);
      }
    }

    console.log(`   ✓ Completed ${name}: ${inserted} inserted/updated, ${skipped} skipped (protected)`);
  }

  console.log("🔄 Updating database primary key sequences...");
  for (const { dbName, hasIdentity } of tablesToImport) {
    if (hasIdentity) {
      try {
        await db.execute(sql.raw(`SELECT setval(pg_get_serial_sequence('"${dbName}"', 'id'), COALESCE(MAX(id), 1)) FROM "${dbName}";`));
      } catch (err: any) {
        // Ignore
      }
    }
  }

  console.log("🎉 Idempotent upsert & merge complete!");
  await pool.end();
}

importAll().catch(console.error);
